working_dir: &working_dir ~/app
version: 2.1
jobs:
  angul:
    
    docker:
      - image: cimg/python:2.7
    steps:
      - checkout
      - run:
          name: Build angular
          
          command: echo Hello, World!;python oz.py
            
      ################################################################
  jav:
      
      docker:
        - image: cimg/python:2.7
      steps:
        - checkout
        - run:
            name: Build java
            
            command: echo Hello, World!;python oz.py
  pyth:
    
    docker:
      - image: cimg/python:2.7
    steps:
      - checkout
      - run:
          name: Build python
          
          command: echo Hello, World!;python oz.py
      
  vu:
      
      docker:
        - image: cimg/python:2.7
      steps:
        - checkout
        - run:
            name: Build vue
            
            command: echo Hello, World!;python oz.py
  nod:
    
    docker:
      - image: cimg/python:2.7
    steps:
      - checkout
      - run:
          name: Build node
          
          command: echo Hello, World!;python oz.py
  angu:
    
    docker:
      - image: cimg/python:2.7
    steps:
      - checkout
      - run:
          name: Build angular
          
          command: echo Hello, World!;python oz.py
            
      ########################################################################
  ja:
      
      docker:
        - image: cimg/python:2.7
      steps:
        - checkout
        - run:
            name: Build java
            
            command: echo Hello, World!;python oz.py
  pyt:
    
    docker:
      - image: cimg/python:2.7
    steps:
      - checkout
      - run:
          name: Build python
          
          command: echo Hello, World!;python oz.py
      
  v:
      
      docker:
        - image: cimg/python:2.7
      steps:
        - checkout
        - run:
            name: Build vue
            
            command: echo Hello, World!;python oz.py
  non:
    
    docker:
      - image: cimg/python:2.7
    steps:
      - checkout
      - run:
          name: Build node
          
          command: echo Hello, World!;python oz.py
      
  
        
        
workflows:
  version: 2.1
  create:
    jobs:
      - angul
      - angu   
      - jav
      - ja
      - pyth
      - pyt  
      - v
      - nod  
      - vu
      - non
          
